[book]
authors = ["Phil Freeman"]
language = "ja"
multilingual = false
src = "text-ja"
title = "実例によるPureScript"

[output.html]
git-repository-url = "https://github.com/gemmaro/purescript-book"
mathjax-support = true